# Configuration for cloudflared setup
# Name of the application
name: cloudflared

# Service definitions for the application
services:
  # Service name: cloudflared
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:2025.10.0
    restart: unless-stopped
    network_mode: host
    environment:
      # https://hub.docker.com/r/cloudflare/cloudflared
      - TUNNEL_TOKEN=
    command: tunnel --no-autoupdate run

# CasaOS specific configuration
x-casaos:
  architectures:
    - amd64
    - arm64
  main: cloudflared
  description:
    en_us: https://hub.docker.com/r/cloudflare/cloudflared/tags?name=2025. | Cloudflared-web is a docker image that packages both cloudflared cli and a simple Web UI to easily start or stop remotely-managed Cloudflare tunnel.
  tagline:
    # Short description or tagline in English
    en_us: Cloudflared
  # Developer's name or identifier
  developer: "ulhano"
  # Author of this configuration
  author: Ulhano
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/cloudflare.png
  thumbnail: ""
  title:
    en_us: Cloudflared
  category: MyCasaOS